spring.application.name=prg04luizcarlosdecastrocarvalho-Backend
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.ftrrnygcrtfsnmpxnvug&sslmode=require
spring.datasource.username=postgres.ftrrnygcrtfsnmpxnvug
spring.datasource.password=CarlosLuiz!...
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.error.include-exception=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=true